[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_NHOST_SUBDOMAIN = ""
  VITE_NHOST_REGION = ""

[context.deploy-preview.environment]  
  VITE_NHOST_SUBDOMAIN = ""
  VITE_NHOST_REGION = ""